- cli/torcx.go
- pkg/multicall/multicall.go
- pkg/tar/untar.go
- torcx.go
This adds initial CLI support for a systemd generator called `torcx-generator`, via multicall argv[0] switch (aliased to `torcx apply`).
It introduces a multicall package based on rkt one, but with direct cobra support and optional proc self-exe symlink following.
> torcx: add a torcx-generator multicall alias

- scripts/build.sh
CGO should be disabled for torcx binary file, unless there are sufficient reasons for enabling CGO. As both libgpgme and fsnotify are not necessarily needed, we can safely disable CGO.
Fixes https://github.com/coreos/torcx/issues/26
> scripts/build: disable cgo for torcx binary

- Documentation/design/paths.md
- cli/common.go
- pkg/torcx/paths.go
This moves torcx rundir from `/var/run/torcx/` to `/run/torcx/`.
Such a change should not have any impact on vanilla systems (where
`/var/run` is a symlink to `/run`), but adds future-proofing to
avoid issues in case of later mounts over `/var`.
> paths: move rundir under /run

- cli/profile_use_image.go
When running `"torcx profile use-image"` with an unknown image name, it panics with an error `"index out of range"`, since args[1] is missing.
Fix it by setting a variable imgPair correctly.
> cli/profile/use-image: check for correct input parameter

- Documentation/schemas/torcx-config-v0.md
- cli/common.go
- pkg/torcx/config.go
- pkg/torcx/paths.go
- pkg/torcx/types.go
This introduces a `torcx-config-v0` JSON input to specify common
torcx configuration. This is mostly useful for torcx-generator, as
it can't be passed custom command-line or environmental flags.
The config file is located by default under `/etc/torcx/config.json`
but can be moved somewhere else by specifying `torcx_config=` as a
kernel boot option.
> cli/common: introduce a common config file

- pkg/torcx/perform.go
This is really only for cosmetic reasons, since it will be set read-only anyway.  Permissions auditing programs might still complain about this otherwise.
> torcx/perform: restrict tmpfs root permissions

- pkg/torcx/store.go
This only affects the tested mode.  Paths/names are not changed.
> torcx/store: follow image symlinks

- fixtures/test-get-profile-v0.json
- pkg/torcx/profile.go
- pkg/torcx/profile_test.go
`TestGetProfile` simply tests if `getProfile()` correctly reads the profile from a given manifest in json format. `TestPutGetProfile` first writes out a json manifest into a file using `putProfile()`, and reads it again using `getProfile()` to verify that.
Also split out _ReadFile + json.Unmarshal_ parts into `getProfile()`, also _json.Marshal + WriteFile_ parts into `putProfile()`.
Partly covers https://github.com/coreos/torcx/issues/31
> pkg/torcx: add unit tests TestGetProfile, TestPutGetProfile

- Documentation/schemas/image-manifest-v0.md
- examples/image-manifest.json
- pkg/torcx/perform.go
- pkg/torcx/propagate.go
- pkg/torcx/types.go
This adds a new `network` field to image-manifest to propagate networkd assets.
A complete sample manifest now looks like this:
```
{
"kind": "image-manifest-v0",
"value": {
"bin": [
"/usr/sbin/cupsd"
],
"network": [
"/lib/systemd/system/cups.network"
],
"units": [
"/lib/systemd/system/cups.service",
"/lib/systemd/system/printer.target.wants/"
]
}
}
```
/cc @dm0-
> generator: add networkd units to image-manifest

- cli/apply.go
- cli/profile.go
- cli/profile_new.go
- cli/profile_use_image.go
- pkg/torcx/profile.go
Do something sensible if /etc/torcx doesn't exist - either ignore the error, or create it, depending on the circumstances.
Fixes: #63
> profile: continue if /etc/torcx doesn't exist

- Documentation/design/paths.md
- cli/apply.go
- cli/common.go
- cli/image_list.go
- cli/profile.go
- cli/profile_check.go
- cli/profile_list.go
- cli/types.go
- ftests/generator_test.go
- ftests/rkt.go
- pkg/torcx/build_constants.go
- pkg/torcx/paths.go
- pkg/torcx/perform.go
- pkg/torcx/profile.go
- pkg/torcx/profile_test.go
- pkg/torcx/types.go
This introduces lower (vendor / oem ) and upper (user) profiles which are merged before applying.
The vendor profile is located by default at `/usr/share/torcx/profiles/vendor.json`.
The pem profile is located by default at `/usr/share/oem/torcx/profiles/oem.json`.
Entries in upper profile can override and mask those in lower profile.
Both profiles are optional from torcx point of view.
Closes https://github.com/coreos/torcx/issues/46
Closes https://github.com/coreos/torcx/issues/68
> profile: introduce upper and lower profiles

- pkg/torcx/profile.go
This fixes a generator bug showing up with a missing next-profile,
by skipping upper profile alltogether in such a case.
> pkg/profile: skip missing upper profile

- Documentation/design/paths.md
- cli/common.go
- cli/common_test.go
- cli/image_fetch.go
- ftests/torcx_image_list_test.go
- pkg/torcx/build_constants.go
- pkg/torcx/paths.go
- pkg/torcx/perform.go
- pkg/torcx/perform_test.go
- pkg/torcx/store.go
This PR introduces support for versioned stores, which are enabled by the generator and the userland tool when a matching os-release is detected. With this change, two additional stores are also conditionally inspected for images:
* versioned-oem: `/usr/share/oem/torcx/store/<CurOSVer>/`
* versioned-user: `/var/lib/torcx/store/<CurOSVer>/`
Fixes: https://github.com/coreos/torcx/issues/74
> store: add support for versioned stores

- pkg/torcx/build_constants.go
This updates torcx to use the canonical path for the os-release file,
instead of the CoreOS specific one.
> pkg: update os-release path

- .travis.yml
This updates Go versions (covering 1.8.x to 1.10.x) and performs a general
cleanup of Travis configuration.
> travis: clean and update Go versions

- examples/torcx.target
This adds an example systemd target unit, which tracks proper
torcx-generator run by checking for the seal file. This example is
lifted from ContainerLinux:
https://github.com/coreos/coreos-overlay/pull/2567
Closes: https://github.com/coreos/torcx/issues/51
> examples: add a target unit for torcx

- Documentation/design/images.md
- Documentation/schemas/image-manifest-v0.md
- internal/torcx/perform.go
- internal/torcx/propagate.go
- internal/torcx/types.go
This introduces a `udev_rules` field in image manifest in order to
propagate udev rules contained within an image.
> image: propagate udev rules files

- fixtures/test-invalid-profile.json
- ftests/generator_test.go
- internal/cli/profile_check.go
- internal/cli/profile_new.go
- internal/torcx/json_input.go
- internal/torcx/perform.go
- internal/torcx/profile.go
- internal/torcx/profile_test.go
- internal/torcx/store.go
- internal/torcx/types.go
This reworks the logic responsible of handling profiles and images, in
order to split internal types and JSON configuration.
It also introduces some additional tests and fixtures.
> internal: rework and split JSON config types

- Documentation/schemas/remote-contents-v1.md
- internal/torcx/json_input.go
- internal/torcx/types.go
This introduces a new remote contents manifest, adding support
for inspecting the contents hosted by a remote.
This manifest will be consumed in the future to automatically populate
the local store from a remote source.
> schemas: add torcx-remote-contents-v1 schema 

- internal/cli/common.go
- internal/cli/common_test.go
- internal/cli/image_list.go
- internal/torcx/build_constants.go
- internal/torcx/paths.go
- internal/torcx/store.go
- internal/torcx/store_test.go
- internal/torcx/types.go
This updates common CLI logic so that the USR mountpoint (usually at
`/usr`) can be adjusted at runtime via the `TORCX_USR_MOUNTPOINT`
environment flag.
> cli/common: make the USR mountpoint a runtime flag

- internal/cli/image_clear_versioned.go
This introduces a `torcx image clear-versioned` subcommand, which takes
care of garbage-collectiong images from versioned stores.
It operates either on a single image name or on whole stores, taking
a list of versions to keep.
> cli/image: add a `clear-versioned` subcommand

- internal/cli/common.go
- internal/cli/common_test.go
- internal/cli/profile_check.go
- internal/cli/profile_populate.go
- internal/cli/torcx.go
- internal/torcx/paths.go
- internal/torcx/remote.go
- internal/torcx/remote_test.go
This implements two additional commands that will be used by `coreos-postinst` in `update_engine`:
* `torcx profile check`
* `torcx profile populate`
> cli: add support for torcx remotes

- glide.lock
- glide.yaml
- vendor/github.com/magiconair/properties/decode.go
- vendor/github.com/magiconair/properties/doc.go
- vendor/github.com/magiconair/properties/integrate.go
- vendor/github.com/magiconair/properties/lex.go
- vendor/github.com/magiconair/properties/load.go
- vendor/github.com/magiconair/properties/parser.go
- vendor/github.com/magiconair/properties/properties.go
- vendor/github.com/magiconair/properties/rangecheck.go
- vendor/github.com/pelletier/go-toml/marshal.go
- vendor/github.com/pelletier/go-toml/toml.go
- vendor/github.com/pelletier/go-toml/tomltree_write.go
- vendor/github.com/spf13/afero/mem/file.go
- vendor/golang.org/x/crypto/openpgp/keys.go
This is to hopefully fix buggy parsing of public keys, see
https://github.com/golang/go/issues/25850
> vendor: bump x/crypto to latest

- Documentation/design/remotes.md
- Documentation/schemas/remote-contents-v1.md
- Documentation/schemas/remote-manifest-v0.md
This fixes several errors in the doc-reference with the actual
implementation, and clarifies locations and filenames.
> docs: fix several mistakes

- Documentation/README.md
This updates the user-docs link in README.
Fixes: https://github.com/coreos/torcx/issues/126
> docs: fix README link

- internal/torcx/remote.go
This allows torcx remotes to be served over plaintext HTTP.
> remote: allow plaintext HTTP in base URLs
